version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "1234:1234"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: node server.js 

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:1234
    depends_on:
      - backend
    command: npm run dev
